server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Проксируем API запросы на бэкенд
    location /api/ {
        proxy_pass         http://backend:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_buffering    off;
    }

    # SPA — всё остальное на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain application/javascript application/json text/css;
}
